version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://db_1ujz_user:NIaZv7HISzr7NYNEZjNLx3bxh8uNC1tH@dpg-d25fu27diees73br4pog-a.oregon-postgres.render.com/db_1ujz?sslmode=require
      - FRONTEND_URL=http://localhost:5173
      - UPLOAD_DIR=/app/uploads
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
