services:
  - type: web
    name: frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --port 10000
    envVars:
      - key: VITE_API_URL
        value: https://<backend-service-name>.onrender.com  # Replace with actual URL after deploying backend

  - type: web
    name: backend
    env: docker
    plan: free
    build:
      context: ./backend
      dockerfilePath: Dockerfile
    startCommand: ""  # your Dockerfile CMD handles this
    envVars:
      - key: DATABASE_URL
        value: postgres://postgres:postgres@<db-service-name>:5432/document_analyzer
      - key: FRONTEND_URL
        value: https://<frontend-service-name>.onrender.com  # Replace after both deployed
      - key: UPLOAD_DIR
        value: /app/uploads
      - key: GOOGLE_API_KEY
        sync: false      # Set in Render dashboard!
      - key: LANGSMITH_API_KEY
        sync: false      # Set in Render dashboard!
    disks:
      - name: uploads
        mountPath: /app/uploads
        sizeGB: 2

  - type: database
    name: db
    databaseName: document_analyzer
    user: postgres
    plan: free
    ipAllowList: []    # Allow connections from any services in this Render account

