services:
  # PostgreSQL Database
  - type: pserv
    name: document-analyzer-db
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.postgres
    dockerContext: ./
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: document_analyzer
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  # Backend Service
  - type: web
    name: document-analyzer-backend
    env: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    port: 8000
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: document-analyzer-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://document-analyzer-frontend.onrender.com
      - key: UPLOAD_DIR
        value: /app/uploads
      - key: GOOGLE_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
    disk:
      name: backend-uploads
      mountPath: /app/uploads
      sizeGB: 1

  # Frontend Service
  - type: web
    name: document-analyzer-frontend
    env: docker
    plan: starter
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    port: 5173
    envVars:
      - key: VITE_API_URL
        value: https://document-analyzer-backend.onrender.com
