services:
  - type: web
    name: frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --port 10000
    envVars:
      - key: VITE_API_URL
        value: https://<backend-service-name>.onrender.com
    # After initial deployment, replace <backend-service-name> with your backend's actual Render service name

  - type: web
    name: backend
    env: docker
    plan: free
    build:
      context: ./backend
      dockerfilePath: Dockerfile
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: FRONTEND_URL
        value: https://<frontend-service-name>.onrender.com
      - key: UPLOAD_DIR
        value: /app/uploads
      - key: GOOGLE_API_KEY
        sync: false       # Set the actual value securely in the Render Dashboard
      - key: LANGSMITH_API_KEY
        sync: false       # Set the actual value securely in the Render Dashboard
    disks:
      - name: uploads
        mountPath: /app/uploads
        sizeGB: 2

databases:
  - name: db
    plan: free
    databaseName: document_analyzer
    user: postgres
